
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Sep 08 11:46:34 CEST 2014
//----------------------------------------------------

package sintaxis;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POR = 34;
  public static final int MI = 15;
  public static final int MAI = 17;
  public static final int PCIERRE = 27;
  public static final int CASE = 22;
  public static final int INT = 36;
  public static final int ARRAY = 4;
  public static final int REG = 5;
  public static final int NOT = 12;
  public static final int AND = 13;
  public static final int IGUAL = 30;
  public static final int FUN = 6;
  public static final int OR = 14;
  public static final int BOOL = 37;
  public static final int CALL = 25;
  public static final int DIV = 35;
  public static final int DIS = 19;
  public static final int CC = 29;
  public static final int IF = 2;
  public static final int CA = 28;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int RETURN = 24;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 43;
  public static final int MENOS = 33;
  public static final int MENOR = 16;
  public static final int SWITCH = 21;
  public static final int IMPORT = 39;
  public static final int MAYOR = 18;
  public static final int ENT = 42;
  public static final int PAP = 26;
  public static final int FLECHA = 38;
  public static final int NP = 40;
  public static final int ELSE = 20;
  public static final int PUNTO = 9;
  public static final int IDEN = 41;
  public static final int WHILE = 3;
  public static final int DEFAULT = 23;
  public static final int FALSE = 11;
  public static final int DP = 7;
  public static final int MAS = 32;
}

